version: 0.2
phases:
  build:
    commands:
      - aws s3 sync html/ "s3://${BUCKET_NAME}" --delete
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/*"